HOSTDIR=./
REMOTEDIR=~/Projects/6Lowpan-testbed/$(shell basename $(CURDIR))
RSYNC_FLAG=-rt
HOSTNAME ?= hostname
EXCLUDE=""

BOARD=samr21-xpro
#BOARD=native
RIOTBASE=/home/$(shell whoami)/SDKs/RIOT

sync:
	rsync $(RSYNC_FLAG) --progress --exclude=$(EXCLUDE) $(HOSTDIR) pi@$(HOSTNAME):$(REMOTEDIR)

flashonly:
	@command -v $(FLASHER) >/dev/null 2>&1 || \
		{ $(COLOR_ECHO) \
		'${COLOR_RED}Flash program $(FLASHER) not found. Aborting.${COLOR_RESET}'; \
		exit 1; }
	$(FLASHER) $(FFLAGS)

